import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { version } from '../../package.json';
import I18nProvider from '@/components/I18nProvider';
import { getCurrentLocale } from '@/locales/server';

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getCurrentLocale()
  return (
    <html lang={locale}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black text-gray-300 flex flex-col min-h-screen`}
      >
        <I18nProvider locale={locale}>
          <main className="flex-grow">{children}</main>
          <footer className="w-full text-center text-xs text-gray-500 p-4 font-mono">
            v{version}
          </footer>
        </I18nProvider>
      </body>
    </html>
  );
}
